[tool.poetry]
name = "bespokelabs-curator"
version = "0.1.0"
description = "Bespoke Labs Curator"
authors = ["Bespoke Labs <company@bespokelabs.ai>"]
readme = "README.md"
packages = [{include = "bespokelabs", from = "src"}]
license = "Apache-2.0"
homepage = "https://github.com/bespokelabsai/curator"
repository = "https://github.com/bespokelabsai/curator"
keywords = ["ai", "curator", "bespoke"]

[tool.poetry.dependencies]
python = "^3.10"
litellm = "*"
pydantic = ">=2.9.2"
datasets = "^3.0.2"
ipython = "^8.29.0"
instructor = "^1.6.3"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"
pandas = "^2.2.3"
xxhash = "^3.5.0"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
twine = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
