[tool.poetry]
name = "bella"
version = "0.1.0"
description = ""
authors = ["Bespoke Labs <company@bespokelabs.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
litellm = "*"
pydantic = ">=2.9.2"
datasets = "^3.0.2"
ipython = "^8.29.0"
instructor = "^1.6.3"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
